---
title: "R Notebook"
output: html_document 
---


```{r}
library(conflicted)
library(dplyr)
conflict_prefer("filter", "dplyr")
 conflict_prefer("select", "dplyr")
library(readr)
library(progeny)
 library(DESeq2)
library(org.Hs.eg.db)
 library(tibble)
library(dorothea)
remove_ensg_version = function(x) gsub("\\.[0-9]*$", "", x)
library(ComplexHeatmap)
library(ggpubr)
library(ggbeeswarm)
library(tidyr)
library(tidyHeatmap)
conflict_prefer("heatmap", "tidyHeatmap")
library(RColorBrewer)
```

```{r}
sampleAnno <- read_csv("../../tables/samplesheet_rnaseq.csv")

count_mat <- read_tsv("../../data/10_rnaseq_pipeline/star_salmon/salmon.merged.gene_counts.tsv")

count_mat = count_mat %>% mutate(gene_id= remove_ensg_version(gene_id))

ensg_to_genesymbol = count_mat %>% select(gene_id, gene_name)
ensg_to_desc = AnnotationDbi::select(org.Hs.eg.db, count_mat$gene_id %>% unique(), keytype = "ENSEMBL", columns = c("GENENAME")) %>%
  distinct(across(ENSEMBL), .keep_all = TRUE)

count_mat = count_mat %>%
  select(c(gene_id, sampleAnno[["sample"]])) %>%
  column_to_rownames("gene_id") %>%
  round() # salmon does not necessarily contain integers


################# Start processing
dds <- DESeqDataSetFromMatrix(countData = count_mat,
                              colData = sampleAnno,
                              design = ~ organoid + treatment + orientation)

```


```{r}
dds = estimateSizeFactors(dds)
dds = estimateDispersions(dds)
gene_expr = getVarianceStabilizedData(dds)
rownames(gene_expr) = ensg_to_genesymbol %>% column_to_rownames("gene_id") %>% .[rownames(gene_expr), ]
```

```{r, fig.width=5, fig.height=6}
pathways_scaled = progeny(gene_expr, scale=TRUE)
pathways = progeny(gene_expr, scale=FALSE)

pathways_scaled %>% as_tibble(rownames="sample") %>% 
  pivot_longer(cols=-sample, names_to="pathway") %>%
  inner_join(sampleAnno) %>%
  mutate(sample = paste0(treatment, "_", organoid, "_", orientation)) %>% 
  heatmap(pathway, sample, value,
          palette_value = circlize::colorRamp2(c(-2, 0, 2), brewer.pal(n=5, name="RdBu")[c(5,3,1)]),
          cluster_columns=FALSE) %>%
  add_tile(treatment) %>% 
  add_tile(organoid) %>% 
  add_tile(orientation)

```

```{r, fig.width=12, fig.height=7}
pathway_tidy = pathways %>% as_tibble(rownames="sample") %>% inner_join(sampleAnno %>% select(-fastq_1, -fastq_2)) %>%
  pivot_longer(cols = colnames(pathways), names_to = "Pathway", values_to="score")

p = pathway_tidy %>% 
  ggplot(aes(x=treatment, y=score)) + facet_wrap(~Pathway, scales="free_y", ncol=4) + geom_quasirandom(aes(color=paste0(organoid, "/", orientation))) + 
  stat_compare_means(vjust=1, method="t.test", paired=TRUE) + theme_bw() 

add_summary(p, fun="mean_se", color="black", size=.5)

```


### Dorothea
```{r}
data(dorothea_hs, package = "dorothea")

regulons = dorothea_hs %>%
  filter(confidence %in% c("A", "B"))

tf_activities <- run_viper(gene_expr, regulons, 
                           options =  list(method = "scale", minsize = 4, 
                                           eset.filter = FALSE, cores = 1, 
                                           verbose = FALSE))
```

```{r, fig.height=20, fig.width=5}
Heatmap(tf_activities,
        cluster_rows = TRUE,
        cluster_columns = TRUE)
```

```{r}
sample_order = sampleAnno %>% arrange(treatment, organoid, orientation) %>% pull("sample")
pvalues = tf_activities[, sample_order] %>% 
  apply(1, function(x) {
    t.test(x[1:4], x[5:8], paired = TRUE)$p.value
  }) 

tf_df = as_tibble(tf_activities, rownames="TF")
tf_df$pvalue = pvalues
tf_df$fdr = p.adjust(pvalues, method="fdr")
tf_df = tf_df %>% arrange(pvalue)
```


```{r, fig.width=5, fig.height=7}
Heatmap(tf_activities[tf_df %>% filter(fdr < 0.1) %>% pull("TF"), sample_order],
        cluster_rows = TRUE,
        cluster_columns = FALSE)
```
